theme: jekyll-theme-minimal
title: Macrophage in the Computer Age
author: Amelia Lucienne Hoyt
email: hoyt.amelia@gmail.com
description: >
  Unraveling the Human Microbiome

github_username:  alhoyt
linkedin_username: ameliahoyt

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
